// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../components/baseCom/app-layout.vue')['default']
    SvgIcon: typeof import('./../components/baseCom/svg-icon/svg-icon.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanNavBar: typeof import('vant/es')['NavBar']
  }
}

export { }
